;;; -*- lexical-binding: t; -*-

;; Copyright (C) 2026

;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License
;; as published by the Free Software Foundation; either version 2
;; of the License, or (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program; if not, write to the Free Software
;; Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
;; 02110-1301, USA.

;;; Code:
(use-package org-roam
  :ensure t
  :commands (org-roam-node-find org-roam-capture
								org-roam-node-insert
								do-org-roam-sync
								do-org-roam-insert)
  :preface
  ;; Add prefix to the sync messages generated by Org-roam
  (with-eval-after-load 'org-roam
	(defun do--org-roam-progress-reporter (orig-fun msg &rest args)
	  (apply orig-fun (concat "Org-roam: " msg) args))

	(advice-add 'org-roam-db-sync :around
				(lambda(orig-fun &rest args)
				  (advice-add 'make-progress-reporter :around #'do--org-roam-progress-reporter)
				  (let ((result (apply orig-fun args)))
					(advice-remove 'make-progress-reporter #'do--org-roam-progress-reporter)
					result))))

  :functions (org-fold-show-all
			  do--auto-revert-note-files
			  do--org-reveal-drawers-in-notes )
  :init
  (general-define-key
   :keymaps 'override
   :states '(normal visual)
   "SPC n" '(:ignore t :which-key "notes")
   "SPC ns" 'org-roam-node-find
   "SPC sn" 'org-roam-node-find
   "SPC nl" 'do-org-roam-insert
   "SPC nL" 'do-org-roam-insert-immediate
   "SPC nc" 'org-roam-capture
   "SPC nC" 'do-org-roam-capture-feeling)

  (general-define-key
   :keymaps 'org-mode-map
   :states '(normal visual)
   "SPC n#" 'org-id-get-create
   "SPC na" 'org-roam-alias-add
   "SPC nA" 'org-roam-alias-remove
   "SPC nt" 'org-roam-tag-add
   "SPC nT" 'org-roam-tag-remove
   "SPC nr" 'org-roam-ref-add
   "SPC nR" 'org-roam-ref-remove
   "SPC nb" 'org-roam-buffer-toggle
   "<M-TAB>" 'completion-at-point)

  (general-define-key
   :keymaps 'org-mode-map
   :states '(insert replace)
   "<M-TAB>" 'completion-at-point)

  (general-define-key
   :keymaps 'org-roam-preview-map
   "h" 'magit-section-backward)

  (general-define-key
   :keymaps 'org-roam-node-map
   "h" 'magit-section-backward)

  :config
  (require 'org-capture)
  (setq org-roam-directory (expand-file-name "~/notes/notebook")
		org-roam-completion-everywhere t ;; completion-at-point
		org-roam-node-display-template "${downtitle}" ;;remove case sensitivity. Check 'org-roam-node-downtitle' in this file
		org-roam-capture-templates
		'(("d" "default" plain "%?"
		   :target (file+head "${slug}-%<%Y%m%d>.org"
							  "#+ARCHIVE: ~/notes/notebook/archive-notes.org\n#+title: ${title}\n")
		   :unnarrowed t)

		  ("m" "math" plain "%?"
		   :target (file+head "${slug}-%<%Y%m%d>.org"
							  "#+ARCHIVE: ~/notes/notebook/archive-notes.org\n#+filetags: :math:\n#+title: ${title}\n")
		   :unnarrowed t)

		  ("3" "3d" plain "%?"
		   :target (file+head "${slug}-%<%Y%m%d>.org"
							  "#+ARCHIVE: ~/notes/notebook/archive-notes.org\n#+filetags: :3d:\n#+title: ${title}\n")
		   :unnarrowed t)

		  ("c" "cs" plain "%?"
		   :target (file+head "${slug}-%<%Y%m%d>.org"
							  "#+ARCHIVE: ~/notes/notebook/archive-notes.org\n#+filetags: :cs:\n#+title: ${title}\n")
		   :unnarrowed t)

		  ("b" "book" plain "%?"
		   :target (file+head "~/notes/notebook/books/${slug}-%<%Y%m%d>.org"
							  "#+ARCHIVE: ~/notes/notebook/archive-notes.org\n#+filetags: :book:\n#+title: ${title}\n")
		   :unnarrowed t)

		  ("f" "fleeting" plain "%?"
		   :target (file+head "~/notes/notebook/fleetings/fleeting-%<%Y%m%d%H%M%S>.org"
							  "#+ARCHIVE: ~/notes/notebook/fleetings/archive-notes.org\n#+filetags: :fleeting:\n#+title: fleeting-%<%Y%m%d%H%M%S>\n")
		   :unnarrowed t)))

  ;; Used by org-roam-node-display-template
  (defun org-roam-node-downtitle (node)
	(downcase (org-roam-node-title node)))

  ;; To avoid opening notes in new windows
  (add-to-list 'org-link-frame-setup '(file . find-file))

  (defun do-org-roam-sync ()
	"Refresh Org-Roam's database."
	(interactive)
	(make-thread
	 (org-roam-db-sync t) "org-roam db sync"))

  ;; launch an idle timer to keep org-roam db sync with note files
  (run-with-idle-timer 300 t #'do-org-roam-sync)

  (org-roam-db-autosync-mode t)

  (require 'evil)
  (evil-define-operator do-org-roam-insert (beginning end &optional type)
	(ignore type)
	(save-excursion
	  (set-mark beginning)
	  (goto-char end)
	  (org-roam-node-insert)))

  (defun do-org-roam-insert-immediate (&rest args)
	(interactive "P")
	(ignore args)
	(let ((org-roam-capture-templates
		   (list (append (car org-roam-capture-templates) '(:immediate-finish t)))))
	  (call-interactively #'do-org-roam-insert nil)))

  (defun do-org-roam-capture-feeling ()
	(interactive)
	(org-roam-capture- :keys "f"  :node (org-roam-node-create)))

  (require 'org-roam-protocol))

(use-package org-roam-ui
  :ensure t
  :after (org-roam)
  :config
  (general-define-key
   :keymaps 'org-mode-map
   :states '(normal visual)
   "SPC nn" 'org-roam-ui-open)
  (setq org-roam-ui-open-on-start nil)
  (org-roam-ui-mode 1))

(use-package latte-roam
  :defer 5
  :load-path "local-packages/latte-roam"
  :hook ((text-mode . latte-roam-mode)
		 (prog-mode . latte-roam-mode))

  :commands (latte-roam-files
			 latte-roam-grep)
  :init
  (general-define-key
   :keymaps 'override
   :states '(normal visual)
   "SPC n" '(:ignore t :which-key "notes")
   "SPC nf" 'latte-roam-files
   "SPC ng" 'latte-roam-grep)

  :config
  (require 'org-roam)
  (require 'counsel)

  (setq latte-roam-directory org-roam-directory
		latte-roam-ignore-words '("attach"))

  (defun latte-roam-files ()
	"Gets list of note files along with their headers."
	(interactive)
	(let ((counsel-fzf-cmd "rg --color never --files -g '*%s*'"))
	  (counsel-fzf nil latte-roam-directory "Note files ")))

  (defun latte-roam-grep (&optional init-input)
	"Interactively search through the notes' text. INIT-INPUT can be passed as the
  initial grep query."

	(interactive)
	;; Pass a regex to ask ag to discard org metadata.
	;;^[] beginning of the line
	;;[^] not
	;; * zero or more char
	;;(counsel-ag "^[^#]\|[ ]*[^:] " "~/notes" "--nomultiline" )
	(unless (fboundp 'counsel)
	  (require 'counsel))
	(setq init-input (or init-input ""))
	(counsel-rg init-input latte-roam-directory "-t org"
				"In-text Search "))

  (defun do--auto-revert-note-files ()
	(let ((file (buffer-file-name)))
	  (when (and file
				 (file-in-directory-p file latte-roam-directory))
		(auto-revert-mode 1))))
  (add-hook 'find-file-hook #'do--auto-revert-note-files)

  (defun do--org-reveal-drawers-in-notes ()
	"If the current Org file is a note, expand all drawers and properties."
	(require 'org-fold)
	(let ((file (buffer-file-name)))
	  (when (and file
				 (file-in-directory-p file latte-roam-directory))
		(save-excursion
		  (goto-char (point-min))
		  (org-fold-show-all)))))
  (add-hook 'org-mode-hook #'do--org-reveal-drawers-in-notes))

(provide 'do-notebook)
