#!/bin/bash

# Enabling nvidia GPU without starting a new x server
# Forked from 'nvidia-xrun'
# Source from Arch wiki:
# https://wiki.archlinux.org/index.php/Dell_XPS_15_7590
# https://raw.githubusercontent.com/noxultranonerit/SimpleScripts/master/nvidia_gpu

CONTROLLER_BUS_ID=0000:00:01.0
DEVICE_BUS_ID=0000:01:00.0
MODULES_LOAD=(nvidia nvidia_modeset nvidia_drm nvidia_uvm)
MODULES_UNLOAD=(nvidia_drm nvidia_modeset nvidia nvidia_uvm)
BLACKLIST=/etc/modprobe.d/nvidia-blacklist.conf
DISABLE_NVIDIA=/etc/modprobe.d/disable-nvidia.conf
XORG_CONFIG=/home/yad/dotfiles/nvidia/system/etc/X11/xorg.conf.d/30-nvidia.conf
INSTALL_XORG_CONFIG=/etc/X11/xorg.conf.d/30-nvidia.conf
ERROR_RETURN_VALUE=1
BUS_RESCAN_WAIT_SEC=1

function gpu_on {

	sudo mv $DISABLE_NVIDIA $DISABLE_NVIDIA.disable 2> /dev/null
	sudo mv $BLACKLIST $BLACKLIST.disable 2> /dev/null
	sudo cp $XORG_CONFIG $INSTALL_XORG_CONFIG 2> /dev/null

	if [ "/sys/bus/pci/devices/${DEVICE_BUS_ID}/power/runtime_status" = "suspended" ]; then
		echo "Error: $ERROR_RETURN_VALUE - Nvidia card loaded already" 1>&2
		exit $ERROR_RETURN_VALUE
	fi

	if [[ $(lsmod | grep nouveau) ]]; then
		echo "Error: $ERROR_RETURN_VALUE - Nouveau module owns the graphic card! Run $0 --init again and reboot, or if you know what you are doing, modprobe -r nouveau modules." 1>&2
		exit $ERROR_RETURN_VALUE
	fi

	echo 'Turning the PCIe controller on to allow card rescan'
	sudo tee /sys/bus/pci/devices/${CONTROLLER_BUS_ID}/power/control <<<on
	echo 'Waiting 1 second'
	sleep ${BUS_RESCAN_WAIT_SEC}

	if [[ ! -d /sys/bus/pci/devices/${DEVICE_BUS_ID} ]]; then
		echo 'Rescanning PCI devices'
		sudo tee /sys/bus/pci/rescan <<<1
		echo "Waiting ${BUS_RESCAN_WAIT_SEC} second for rescan"
		sleep ${BUS_RESCAN_WAIT_SEC}
	fi

	echo 'Turning the card on'
	sudo tee /sys/bus/pci/devices/${DEVICE_BUS_ID}/power/control <<<on

	for module in "${MODULES_LOAD[@]}"; do
		echo "Loading module ${module}"
		sudo modprobe ${module}
	done
}

function gpu_off {

	sudo mv $DISABLE_NVIDIA.disable $DISABLE_NVIDIA 2> /dev/null
	sudo mv $BLACKLIST.disable $BLACKLIST 2> /dev/null
	sudo rm $INSTALL_XORG_CONFIG 2> /dev/null

	if [[ ! $(lsmod | grep nvidia) ]]; then
		echo "Error : $ERROR_RETURN_VALUE - No Nvidia card loaded" 1>&2
		exit $ERROR_RETURN_VALUE
	fi

	for module in "${MODULES_UNLOAD[@]}"; do
		echo "Unloading module ${module}"
		sudo modprobe -r ${module} -f
	done

	if [[ $(lsmod | grep nvidia) ]]; then
		echo "Error : $ERROR_RETURN_VALUE - Module unload failed. Run nvidia-smi to check running process and kill them " 1>&2
		exit $ERROR_RETURN_VALUE
	else
		echo 'Removing Nvidia bus from the kernel'
		sudo tee /sys/bus/pci/devices/${DEVICE_BUS_ID}/remove <<<1
		echo 'Enabling powersave for the PCIe controller'
		sudo tee /sys/bus/pci/devices/${CONTROLLER_BUS_ID}/power/control <<<auto
	fi

}

function help {
	cat <<EOF
Help Menu:
	'nvidia-cli on'  to turn the nvidia GPU on
	'nvidia-cli off' to turn the nvidia GPU off
EOF
}

case $1 in
	"on") gpu_on ;;
	"off") gpu_off ;;
	*) help ;;
esac
