#! /bin/sh

COLOR_BG="#000000"
COLOR_FG="#e6beae"

FONT=$(xrdb -query | awk '/^Panel.font1:/ {for(i=2; i<=NF; i++) printf "%s%s", $i, (i==NF?ORS:FS)}')
HEIGHT=$(xrdb -query | awk '/^Panel.height:/ {for(i=2; i<=NF; i++) printf "%s%s", $i, (i==NF?ORS:FS)}')
