#!/bin/bash

# Copyright (C) 2026

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# Desktop-aware launcher for Firefox. We launch Firefox either in the VPN mode
# or not depending on the current focused desktop. If the VPN mode is
# activated, then Firefox sends that data through VPN. Otherwise, data is
# sent directly.

# exec /usr/bin/firefox -P "vpn" &> /dev/null

exec lxc exec browser-vpn -- sudo -u lxd --login librewolf
