#!/bin/sh

# Copyright (C) 2019

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.


bspc config border_width 1
bspc config window_gap 0
bspc config pointer_follows_monitor true
# bspc config automatic_scheme longest_side
# bspc config initial_polarity second_child
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config ignore_ewmh_focus false

bspc config normal_border_color $(xrdb -query | awk '/\*color15:/{print $2}')
bspc config active_border_color $(xrdb -query | awk '/\*color0:/{print $2}')
bspc config focused_border_color $(xrdb -query | awk '/\*color7:/{print $2}')
bspc config presel_feedback_color $(xrdb -query | awk '/\*color0:/{print $2}')

# bspc config external_rules_command $HOME/.config/bspwm/first-win-fixed.sh
# $HOME/.config/bspwm/ultrawide-aware.sh &> /dev/null &

# Remove old rules
bspc rule -r '*'
# Write the new rules
bspc rule -a 'Zathura' follow=on desktop=8 state=tiled
bspc rule -a 'dmenu' manage=off
bspc rule -a 'Emacs' follow=on state=tiled
bspc rule -a 'Emacs:music-playlist' follow=on desktop=9
bspc rule -a 'Emacs:scratch-buffer' follow=on state=floating sticky=on center=on
bspc rule -a 'Emacs:calculator' follow=on state=floating sticky=on center=on
bspc rule -a 'URxvt:pulsemixer' follow=on state=floating sticky=on center=on
bspc rule -a 'URxvt:htop' follow=on desktop=10 state=tiled
bspc rule -a 'URxvt:glances' follow=on desktop=10 state=tiled
bspc rule -a 'URxvt:log' follow=on desktop=10 state=tiled
bspc rule -a 'Steam' follow=on state=tiled sticky=off desktop=5

# Set the general setting for DPI
xrandr --auto
xrandr --dpi 200

# Set the background color
feh --bg-fill $(ls ${HOME}/pictures/background/* | shuf -n 1) &

# Fix the mouse size
xsetroot -xcf /usr/share/cursors/xorg-x11/Adwaita/cursors/left_ptr 16 &

systemctl --user import-environment
systemctl --user start emacs-26.service &
systemctl --user restart sxhkd@${XDG_VTNR}.service &

# Disable key stroke repeating
xset r off

# Startup commands
gpg-connect-agent /bye
