#!/bin/sh

# Setup env.
. $HOME/bin/settings.sh

bspc config border_width 1
bspc config window_gap 0
bspc config pointer_follows_monitor true
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
# bspc config automatic_scheme spiral
# bspc config initial_polarity first_child

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus false

bspc config normal_border_color $COLOR_ACTIVE
bspc config active_border_color $COLOR_ACTIVE
bspc config focused_border_color $COLOR_ACTIVE2
bspc config presel_feedback_color $COLOR_ACTIVE
bspc config external_rules_command $HOME/.config/bspwm/external/same-size-mode.sh

bspc rule -a 'Zathura' follow=on desktop=8 state=tiled
bspc rule -a 'dmenu' manage=off
bspc rule -a 'Emacs' follow=on state=tiled
bspc rule -a 'Emacs:music-playlist' follow=on desktop=9
bspc rule -a 'Emacs:scratch-buffer' follow=on state=floating sticky=on center=on
bspc rule -a 'Emacs:calculator' follow=on state=floating sticky=on center=on

bspc monitor DP-2 -n DP-2 -d 10

# Set the background color
xsetroot -solid $COLOR_BACKGROUND &

# launch the bar
$HOME/.config/lemon-bar/panel.sh &

# Fix the mouse size
xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 16 &

# Keybindings
systemctl --user restart sxhkd.service


# Startup commands
gpg-connect-agent /bye
