#!/bin/sh

# Copyright (C) 2019

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# Setup env.
. $HOME/bin/settings.sh

bspc config border_width 1
bspc config window_gap 0
bspc config pointer_follows_monitor true
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
# bspc config automatic_scheme spiral
# bspc config initial_polarity first_child

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config ignore_ewmh_focus false

bspc config normal_border_color $COLOR_ACTIVE
bspc config active_border_color $COLOR_ACTIVE
bspc config focused_border_color $COLOR_ACTIVE2
bspc config presel_feedback_color $COLOR_ACTIVE
bspc config external_rules_command $HOME/.config/bspwm/first-win-fixed.sh
$HOME/.config/bspwm/ultrawide-aware.sh &> /dev/null &

bspc rule -a 'Zathura' follow=on desktop=8 state=tiled
bspc rule -a 'dmenu' manage=off
bspc rule -a 'Emacs' follow=on state=tiled
bspc rule -a 'Emacs:music-playlist' follow=on desktop=9
bspc rule -a 'Emacs:scratch-buffer' follow=on state=floating sticky=on center=on
bspc rule -a 'Emacs:calculator' follow=on state=floating sticky=on center=on

bspc monitor DP-2 -n DP-2 -d 10

# Set the background color
xsetroot -solid $COLOR_BACKGROUND &

# Fix the mouse size
xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 16 &

# Keybindings
systemctl --user start sxhkd.service &

# launch the bar
systemctl --user start lemon-bar.service &

# Startup commands
gpg-connect-agent /bye
# Disable key repeat
xset r off
