#!/bin/bash

# Copyright (C) 2020

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

gpu(){
	local status=$(cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_status 2> /dev/null || echo igpu)

	if [ "$status" == "active" ]; then
		echo -e "\x04  dGPU \x01 "
	else
		echo -e ""
	fi
}

temp(){
	local cpu=$(sensors k10temp-pci-00c3 | awk '/Tctl/{gsub("+", "",$2); print $2}')
	# local water=$(sensors it8792-isa-0a60 | awk '/temp2/{gsub("+", "",$2); print $2}')
	# echo -e " $cpu  $water "
	echo -e " $cpu "
}

fan(){
	local fan1=$(sensors amdgpu-pci-* | awk '/fan/{gsub("+", "",$2); print $2}')
	if [ $fan1 -ge 700 ]; then
		echo -e "\x07  $fan1 RPM \x01 "
	elif [ $fan1 -ge 1000 ]; then
		echo -e "\x04  $fan1 RPM \x01 "
	elif [ $fan1 -ge 1500 ]; then
		echo -e "\x05  $fan1 RPM \x01 "
	else
		echo -e " $fan1 RPM "
	fi
}

mem(){
	local m=$(free | awk '/^Mem/{$1=sprintf("%.1f",($2-$7)/(1024^2)); print $1}')
	if (( $(echo $m'>'80 | bc ) )); then
		m="\x05  ${m}GB \x01 "
	elif (( $(echo $m'>'50 | bc ) )); then
		m=" ${m}GB "
	else
		m=""
	fi
	echo -e "$m"
}

emacs(){
	local v=$(emacsclient -a=/bin/true -ne '(length (do-list-buffers))' | bc)
	if [ ! -z "$v" ]; then
		echo -e " $v "
	fi
}

keyboard(){
	local layout=$(setxkbmap -query |
					   awk '/^layout/{split($2,arr,","); print toupper(arr[1])}')
	local variant=$(setxkbmap -query |
						awk '/^variant/{split($2,arr,","); print toupper(arr[1])}')
	local caps=$(xset -q | awk '/Caps/{print $4}')
	local state=''
	if [ "$variant" != "DVORAK" ]; then
		state="\x04  $layout \x01 "
	else
		state=""
	fi
	if [ "$caps" = 'off' ]; then
		echo -e "$state"
	else
		echo -e "\x05  CAPS \x01 $state"
	fi
}

vol(){
	local v=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100}')
	local muted=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $3}')
	if [ "$muted" = '[MUTED]' ]; then
		v="\x05  ${v}% \x01 "
	elif [ $v = 0 ]; then
		v="\x04  \x01 "
	else
		v=" ${v}% "
	fi
	echo -e "$v"
}

load(){
	local r=$(echo $(cut -f 1 -d ' ' /proc/loadavg)*100/$(nproc) | /usr/bin/bc)
	if [ $r -ge 80 ]; then
		echo -e "\x05  $r% \x01 "
	elif [ $r -ge 50 ]; then
		echo -e "\x04  $r% \x01 "
	elif [ $r -ge 25 ]; then
		echo -e "\x07  $r% \x01 "
	elif [ $r -ge 5 ]; then
		echo -e " $r% "
	else
		echo -e ""
	fi
}

energy_profile(){
	local v=$(cat /sys/devices/system/cpu/cpufreq/policy0/energy_performance_preference)
	if [ $v = "power" ]; then
		echo -e "\x06  SAVE \x01 "
	elif [ $v = "performance" ]; then
		echo -e "\x06  PRFM \x01 "
	elif [ $v = "balance_performance" ]; then
		echo -e " BLPR "
	else
		echo -e " $v "
	fi
}

vpn(){
	local v=$(ip route | head -n 1 | grep 'tun0')
	if [ -z "$v" ]; then
		echo -e "\x05  OFF \x01 "
	else
		echo -e " ON "
	fi
}

syncthing_progress(){
    local output
    output=$(lxc exec syncthing -- sudo -u lxd syncthing cli show pending devices 2>/dev/null | tr -d '[:space:]')
    # If Syncthing isn't running, the output will be empty
    if [ -z "$output" ]; then
	echo -e "\x02  \x01 "
    elif [ "$output" = "[]" ] || [ "$output" = "{}" ] || [ "$output" = "null" ]; then
	true
    else
	echo -e "\x04 ️ \x01 "
    fi
}

time_left(){
	printf " %'d " $(life)
}

status="$(temp)$(load)$(mem)$(synthing_progress)$(vpn)$(keyboard)$(vol)| $(time_left)| $(date +'%a, %b %d %H:%M')"
status=$(echo -e "$status" | tr '\n' ' ')
xsetroot -name "$status"
