xrandr --auto

# load Xresources if it exists
[[ -f $HOME/.Xresources ]] && xrdb -merge -I$HOME $HOME/.Xresources

# Startup commands
# BSPWM
# exec bspwm

#DWM
sleep 1 | $HOME/.config/dwm/dwmrc &
exec dwm
