#!/bin/sh

# Copyright (C) 2020

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# Set the general setting for DPI
xrandr --auto

# Set the background color
feh --bg-fill $(ls ${HOME}/pictures/background/* | shuf -n 1) &

# Fix the mouse size
xsetroot -xcf /usr/share/cursors/xorg-x11/Adwaita/cursors/left_ptr 16 &

systemctl --user import-environment
# Avoid using systemd 'enable' feature for Emacs as it can launch Emacs server
# before importing most all env. variables. Instead, start Emacs service
# manually in the beginning of a new BSPWM session.
systemctl --user start emacs-27-vcs.service &
systemctl --user restart sxhkd-dwm@${XDG_VTNR}.service &

# Disable key stroke repeating
xset r off

# Startup commands
gpg-connect-agent /bye


while [ 1 ]; do

	fan=$(sensors |
			  awk '/^fan1/{print $2}/^fan2/{print $2}' |
			  tr '\n' ' ')
	mem=$(free |
		awk '/^Mem/{print ($2-$7)/(1024^2)}' |
		bc |
		awk '{$1=sprintf("%.1f",$0); if ( int($1) < 24) print $1 "GB" ; else print "%{F'$(xrdb -query | awk '/\*color11:/{print $2}')'}" $1 "GB%{F-}";}')
	keyboard=$(setxkbmap -query |
				awk '/^layout/{split($2,arr,","); print toupper(arr[1])}')
	caps=$(xset -q | awk '/Caps/{print $4}')
	vol=$(pulsemixer --get-volume | awk '{print $1}')
	batCode=$(acpi | awk '{print tolower(substr($3,1,length($3)-1))}')
	batLevel=$(acpi |  awk '{gsub(",","",$0);gsub("%","",$0);print $4}')
	batTime=$(acpi | awk '{print $5}')

	xsetroot -name "  $fan|  $mem |  $batLevel $batTime $batCode |  $vol |  $caps  $keyboard | $(date +'%a, %b %d %H:%M')"
	sleep 1m
done
