#!/bin/sh

# Copyright (C) 2020

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# Set the general setting for DPI
xrandr --auto

# Set the background color
feh --bg-fill $(ls ${HOME}/pictures/background/* | shuf -n 1) &

# Fix the mouse size
xsetroot -xcf /usr/share/cursors/xorg-x11/Adwaita/cursors/left_ptr 16 &

systemctl --user import-environment
# Avoid using systemd 'enable' feature for Emacs as it can launch Emacs server
# before importing most all env. variables. Instead, start Emacs service
# manually in the beginning of a new BSPWM session.
systemctl --user start emacs-27-vcs.service &
systemctl --user restart sxhkd-dwm@${XDG_VTNR}.service &

# Disable key stroke repeating
xset r off

# Startup commands
gpg-connect-agent /bye


while [ 1 ]; do
	xsetroot -name "$(date +' %a, %b %d %H:%M:%S')"
	sleep 1s
done
