#!/bin/bash

# Copyright (C) 2020

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# Set the general setting for DPI
xrandr --auto

# Set the background color
feh --bg-fill $(/bin/ls ${HOME}/pictures/background/* | shuf -n 1) &

systemctl --user import-environment DISPLAY HOME USER UID

# Avoid using systemd 'enable' feature for Emacs as it can launch Emacs server
# before importing most all env. variables. Instead, start Emacs service
# manually in the beginning of a new dwm session.
systemctl --user restart emacs-29-vcs.service &

setxkbmap # Make sure X11 keymap is loaded properly before starting sxhkd
systemctl --user restart sxhkd@${XDG_VTNR}.service &

# Trigger local pulseaudio service
pulsemixer -l &> /dev/null
# systemctl --user start pulseaudio.service &
systemctl --user start dwmbar.timer &

# Disable key stroke repeating
xset r off

# Startup commands
gpg-connect-agent /bye
